"""update the Role and User model

Revision ID: 193f0fa8bf72
Revises: b5bd76bb6202
Create Date: 2023-09-06 12:45:03.383150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193f0fa8bf72'
down_revision = 'b5bd76bb6202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=130), nullable=True))

    # ### end Alembic commands ###
