"""Optimize the Gravatar resources

Revision ID: 78168659e85a
Revises: f2e39fae1af6
Create Date: 2023-09-14 11:21:17.626412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78168659e85a'
down_revision = 'f2e39fae1af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_hash', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_hash')

    # ### end Alembic commands ###
