"""update the model

Revision ID: 990513b33e05
Revises: 193f0fa8bf72
Create Date: 2023-09-06 17:02:54.843850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990513b33e05'
down_revision = '193f0fa8bf72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
